site_name: BIPACKAGE
theme:
  name: material
  font:
    code: JetBrains Mono
    size: 2
  features:
    - toc.integrate
    - navigation.top
    - content.code.copy
    - navigation.sections
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      
  extensions:
    - toc:
        permalink: true
        toc_depth: 0

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            separate_signature: true
            show_root_toc_entry: false
            heading_level: 1
            

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets

nav:
  - Installation: index.md
  - BIP API:
    - Home: bip/index.md
    - Bamtools:
      - bam_counts: bip/bam_counts.md
      - compile_bam_stats: bip/compile_bam_stats.md
    - Bedtools:
      - bedfilegenerator: bip/bedfilegenerator.md
    - Fastqtools:
      - downsample: bip/downsample.md
      - fastq_read_counter: bip/fastq_read_counter.md
      - fastqvalidate: bip/fastqvalidate.md
      - merge_it: bip/merge_it.md
      - undetermined_demultiplexer: bip/undetermined_demultiplexer.md
    - ittools:
      - check_gzip_validity: bip/check_gzip_validity.md
      - check_reconnect: bip/check_reconnect.md
      - is_mounted: bip/is_mounted.md
      - md5sumchecker: bip/md5sumchecker.md
      - mount_server: bip/mount_server.md
    - NiptTools:
      - nipt_bcl2fastq: bip/nipt_bcl2fastq.md
  - BIP CLI:
    - Home: bip-CLI/index.md
    - Bamtools:
      - bam_counts: bip-CLI/bam_counts.md
      - compile_bam_stats: bip-CLI/compile_bam_stats.md
    - Bedtools:
      - bedfilegenerator: bip-CLI/bedfilegenerator.md
    - Fastqtools:
      - downsample: bip-CLI/downsample.md
      - fastq_read_counter: bip-CLI/fastq_read_counter.md
      - fastqvalidate: bip-CLI/fastqvalidate.md
      - merge_it: bip-CLI/merge_it.md
      - undetermined_demultiplexer: bip-CLI/undetermined_demultiplexer.md
    - ittools:
      - check_gzip_validity: bip-CLI/check_gzip_validity.md
      - check_reconnect: bip-CLI/check_reconnect.md
      - is_mounted: bip-CLI/is_mounted.md
      - md5sumchecker: bip-CLI/md5sumchecker.md
      - mount_server: bip-CLI/mount_server.md
    - NiptTools:
      - nipt_bcl2fastq: bip-CLI/nipt_bcl2fastq.md


  - BIPIPE CLI:
    - bwa_dedup: bipipe-CLI/bwa_dedup.md
    - gatk_gcnv: bipipe-CLI/gatk_gcnv.md
    - cnv_pon: bipipe-CLI/cnv_pon.md
    - snv_indel: bipipe-CLI/snv_indel.md
    - cnv: bipipe-CLI/cnv.md

    